server:
  port: 7000
  servlet:
    context-path: /ad-sponsor

spring:
  application:
    name: euraka-client-ad-sponsor
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/ads?autoReconnect=true
    username: root
    password: root
    tommcat:
      max-active: 4
      min-idle: 2
      initial-size: 2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/euraka/
